### ISSUE TITLE
Write bio

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/data-cleaning-course#13]

**Comment by dgkeyes** [comment]
@luisDVA can you please provide a short bio for the website? Here is Dana's for reference:

> This course is taught by Dana Wanzer, Assistant Professor in the Psychology Department at the University of Wisconsin, Stout. An avid R user, Dana has extensive experience in advanced statistical techniques. She is well-versed in such techniques as exploratory and confirmatory factor analysis, structural equation modeling, multilevel modeling, and more.

**Comment by luisDVA** [comment]
here's a brief bio. feel free to edit for style, spelling, grammar, and content.

This course is taught by Luis D. Verde Arregoitia. Luis is a biologist by training and an R enthusiast since 2011. Alongside his research on mammals, Luis has also spent years helping and teaching others to overcome the most overlooked steps in data analysis and visualization with R. This includes cleaning, restructuring, and finally sharing analysis-ready data. Luis is an RStudio certified ‘tidyverse’ instructor, and he enjoys teaching and blogging about R in both English and Spanish.

**Comment by dgkeyes** [comment]
Perfect! I updated it just slightly. Here's the final version:

Luis D. Verde Arregoitia is a biologist by training with nearly a decade of R experience. Alongside his research on mammals, Luis has also spent years helping others learn to clean, restructure, and share analysis-ready data. An RStudio certified instructor, he enjoys teaching and blogging about R in both English and Spanish.
